#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

a=0  # Initialize the counter

while [ $a -lt 10 ]
do
	((a++))  # Increment the counter
	if [ $a -eq 4 ]; then
		echo "bad luck"  # Display for 4th iteration
	elif [ $a -eq 8 ]; then
		echo "good luck"  # Display for 8th iteration
	else
		echo "Best School"  # Display for other iterations
	fi
done
